### ISSUE TITLE
Chore - Change naming for LBP Wrapper and factory

### ISSUE THREAD

**Issue by Zitzak** [PrimeDAO/contracts-v2#111]
## User Story
As a developer, I want to understand the purpose of a contract by reading its name so that it is clear what the code should achieve.

## Status Quo
Right now there are a lot of unclear naming which is misleading.

## Acceptance Criteria
We changed the names in a way that it is clear what the purpose of the contract is.

**Comment by Zitzak** [comment]
What were to suggested names we should change them to? I think
- PrimeLBPWrapper
- PrimeLBPWrapperFactory
What do you think @codebuster22

**Comment by codebuster22** [comment]
Hm, I think `LBPWrapper` is good, for `WrapperFactory` we can rename it to `LBPWrapperFactory`.
LBPWrapper tells me that it is a Wrapper of LBP.
and LBPWrapperFactory tells me that it is Factory of LBPWrapper.
