### ISSUE TITLE
Feature - Add possibility to subtract fee from LBP funding

### ISSUE THREAD

**Issue by Zitzak** [PrimeDAO/contracts-v2#117]
## User Story
As a DAO, I want to add a fee to the LBP, so that I can get rewarded for the service I provide.

## Status Quo
- Currently, we have no possibility to add a fee for PrimeDao for providing the LBP service

## Acceptance Criteria
- we are able to add a fee, even tho the DAO is not the liquidity provider.
- the fee gets provided every time through the dapp and passed to the `LBPManager` by the `LBPManagerFactory`
- the fee gets subtracted when the pool is getting funded.
- the fee gets paid in project tokens
- tests are written for the implementation

**Comment by Zitzak** [comment]
We decided on setting the fee to 0% for the first version. Is this something we set in the `Factory` or are we providing the percentage in the frontend so it will be changeable for the future? @codebuster22

**Comment by codebuster22** [comment]
now, we take fee in project tokens upfront. no need for BPT tokens

**Comment by Zitzak** [comment]
Oke I'll change the issue to reflect the recent decisions
