### ISSUE TITLE
Chore - Add states to LBP contract

### ISSUE THREAD

**Issue by Zitzak** [PrimeDAO/contracts-v2#132]
## User Story
As a PrimeDao, I want to clear defined states of the LBP, so that I can enable functionalities that are accessible in each state.

## Status Quo
Currently, we only have the state `isInitialzed` in the contract.

## Acceptance Criteria
- Add these stated
  - Live - between Start date & End date
  - Complete/ended - the end date of an LBP has been reached (name TBD) 
  - UnInitialized - the pool has not been funded yet from the wrapper

**Comment by codebuster22** [comment]
hm, we don't want to add this states to contract. This are for UI and to understand the flow. This states are decided based on current state of LBP.
For example, if the current time is between start date and end date, UI, says live.
if current time is past end time, the UI says complete/ended.

**Comment by codebuster22** [comment]
We would like to add `beneficiary` state to LBPWrapper. For collecting fees. This would be set  in `initializeLBP`

**Comment by Zitzak** [comment]
I'm not sure what you mean by `beneficiary`. Do you mean the fee for the creation of the LBP? And would that not be PrimeDao, set in the factory?

**Comment by codebuster22** [comment]
yes, beneficiary is PrimeDAO
This the terminology used in Seed.
