### ISSUE TITLE
Chore: Test boundary conditions for price calculations of Seed.

### ISSUE THREAD

**Issue by codebuster22** [PrimeDAO/contracts-v2#204]
## User Story
As a developer, I would want to be sure that the calculations work with the boundary conditions too.

## Status Quo
Currently the tests work with normal conditions that are in normal domain.

## Acceptance Criteria
Should have checked boundary conditions and also values that might be outside the domain.

**Comment by Zitzak** [comment]
Mihir did the boundary test so this issue can be closed
